# User Story Map Tool Configuration

app:
  port: 4000
  baseUrl: http://localhost:4000
  logLevel: debug

# TCRT Integration Settings
tcrt:
  apiBaseUrl: http://localhost:9999/api
  requestTimeout: 10000

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:-default-secret-key}
  expiresIn: 7d

# Database Configuration
database:
  mongo:
    uri: ${MONGO_URI:-mongodb://localhost:27017/storymap}
    options:
      retryWrites: true
      w: majority

# Session Configuration
session:
  maxAge: 604800  # 7 days

# API Configuration
api:
  rateLimit:
    windowMinutes: 1
    maxRequests: 60
  tokens:
    hashAlgorithm: sha256
    defaultExpiryDays: 90

# Audit Configuration
audit:
  enabled: true
  retentionDays: 90

# Logging Configuration
logging:
  format: json
  level: debug

# Cors Configuration
cors:
  origin: '*'
  credentials: true
